databases:
  - name: schema-registry-db
    databaseName: schema_registry
    user: schema_registry

services:
  - type: web
    name: schema-registry-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PORT
        value: 10000
      - key: API_KEY
        generateValue: true
      - key: SEED_DIR
        value: /app/seeds
      - key: DATABASE_URL
        fromDatabase:
          name: schema-registry-db
          property: connectionString
